# -*- coding: utf-8 -*-
"""5d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12nFOaPDKQoqeX2609NqukiucHLugpW21
"""

# ================== 0. Setup & imports ==================
import argparse
import math
import sys
from pathlib import Path

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression, Ridge
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import TransformedTargetRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor

from metrics_utils import compute_regression_metrics

ALL_FEATURES = ["temp", "loading", "conc"]
TARGET_UNITS = {
    "thcond": "W/(m·K)",
    "spheat": "J/(kg·K)",
    "density": "kg/m³",
    "visc": "mPa·s",
}


def parse_args():
    parser = argparse.ArgumentParser(
        description="Train and compare regression models for thermophysical properties."
    )
    parser.add_argument("--csv", help="Path to the input CSV file.")
    parser.add_argument(
        "--features",
        nargs="+",
        help="Feature columns to use (for example: temp loading conc).",
    )
    parser.add_argument(
        "--output-dir",
        default="outputs",
        help="Directory where parity plots will be saved (default: outputs).",
    )
    parser.add_argument(
        "--no-plots",
        action="store_true",
        help="Skip parity plot generation.",
    )
    return parser.parse_args()


def load_csv_path(csv_path=None):
    """Return the path to a CSV file, either from CLI input or a prompt."""
    if csv_path:
        return csv_path

    try:
        from google.colab import files

        uploaded = files.upload()
        if not uploaded:
            raise ValueError("No file uploaded.")
        return list(uploaded.keys())[0]
    except Exception:
        prompt = input("Enter the CSV path: ").strip()
        if not prompt:
            raise SystemExit("No CSV path provided.")
        return prompt


def select_independent_params(available, requested=None):
    """Return a non-empty list of feature columns in canonical order."""
    ordered = [c for c in ALL_FEATURES if c in available]
    if not ordered:
        raise ValueError(
            "Data must include at least one of: temp, loading, conc. "
            f"Found columns: {list(available)}"
        )

    if requested:
        picked = [c for c in requested if c in ordered]
        if not picked:
            raise ValueError(f"None of the requested features are available: {requested}")
        return picked

    print(f"Available features: {', '.join(ordered)}")
    line = input(
        "Enter feature names separated by commas (default: all available): "
    ).strip()
    if not line:
        return ordered

    picked = [name.strip() for name in line.split(",") if name.strip()]
    bad = [name for name in picked if name not in ordered]
    if bad:
        raise ValueError(f"Unknown or unavailable columns: {bad}. Use: {ordered}")
    if not picked:
        return ordered
    return [c for c in ordered if c in picked]


# ================== 1. Configuration & auto‑detection ==================
def detect_targets(df):
    if {"thcond", "spheat"}.issubset(df.columns):
        return "thcond", "spheat"
    if {"density", "visc"}.issubset(df.columns):
        return "density", "visc"
    raise ValueError(
        "Could not find expected target columns. "
        "File must contain either (thcond, spheat) or (density, visc)."
    )


# ================== 3. Helpers ==================
def metrics(ytrue, ypred):
    metrics_dict = compute_regression_metrics(ytrue, ypred)
    return (
        metrics_dict["r2"],
        metrics_dict["mae"],
        metrics_dict["rmse"],
        metrics_dict["mape"],
        metrics_dict["aad"],
        metrics_dict["mae_pct_of_mean"],
    )


def metric_label(metric_name, target_name):
    unit = TARGET_UNITS.get(target_name)
    return f"{metric_name} [{unit}]" if unit else metric_name


def print_metrics(name, target, ytrue, ypred, dataset_label="test"):
    r2, mae, rmse, mape, aad, mae_pct_mean = metrics(ytrue, ypred)
    print(
        f"{name:25s} - {target:8s} [{dataset_label}] R2={r2:.4f}, "
        f"{metric_label('MAE', target)}={mae:.4f}, "
        f"{metric_label('RMSE', target)}={rmse:.4f}, "
        f"MAPE (%)={mape:.4f}, "
        f"AAD (%)={aad:.4f}, "
        f"MAE% of Mean={mae_pct_mean:.4f}"
    )


def print_linear_like_formula(model, target_name, label, feature_names):
    coef = model.coef_
    inter = model.intercept_
    print(f"{label} formula for {target_name}")
    parts = [f"{inter:.6f}"]
    for c, fn in zip(coef, feature_names):
        parts.append(f" + {c:.6f}*{fn}")
    print(f"{target_name} = " + "".join(parts))
    print()


def print_poly_formula(pipe, target_name, degree, feature_names):
    polystep = pipe.named_steps["poly"]
    linstep = pipe.named_steps["lin"]
    names = polystep.get_feature_names_out(feature_names)
    coefs = linstep.coef_
    inter = linstep.intercept_

    print(f"Polynomial deg{degree} formula for {target_name}")
    expr = f"{target_name} = {inter:.6f}"
    for name, c in zip(names[1:], coefs[1:]):
        expr += f" + {c:.6f}*{name}"
    print(expr)
    print()


def make_models(polydegree=2):
    return [
        ("Linear Regression", LinearRegression()),
        (
            f"Polynomial Regression deg{polydegree}",
            Pipeline(
                [
                    ("poly", PolynomialFeatures(degree=polydegree, include_bias=False)),
                    ("lin", LinearRegression()),
                ]
            ),
        ),
        (
            "Random Forest",
            RandomForestRegressor(n_estimators=200, random_state=42, n_jobs=-1),
        ),
        (
            "Gradient Boosting",
            GradientBoostingRegressor(
                n_estimators=300,
                learning_rate=0.05,
                max_depth=3,
                random_state=42,
            ),
        ),
        (
            "XGBoost",
            XGBRegressor(
                n_estimators=300,
                learning_rate=0.05,
                max_depth=4,
                subsample=0.9,
                colsample_bytree=0.9,
                random_state=42,
                n_jobs=-1,
            ),
        ),
        ("Ridge Regression", Ridge(alpha=1.0)),
        ("KNN", KNeighborsRegressor(n_neighbors=5, weights="distance")),
        (
            "Neural Network",
            TransformedTargetRegressor(
                regressor=Pipeline(
                    [
                        ("scaler", StandardScaler()),
                        (
                            "mlp",
                            MLPRegressor(
                                hidden_layer_sizes=(64, 32),
                                activation="relu",
                                alpha=0.05,
                                learning_rate_init=0.001,
                                max_iter=2000,
                                random_state=42,
                            ),
                        ),
                    ]
                ),
                transformer=StandardScaler(),
            ),
        ),
        (
            "CatBoost",
            CatBoostRegressor(
                iterations=300,
                learning_rate=0.05,
                depth=6,
                random_seed=42,
                verbose=0,
            ),
        ),
    ]


def example_new_row(feature_names):
    defaults = {"temp": 55.0, "loading": 0.3, "conc": 0.8}
    return pd.DataFrame({fn: [defaults[fn]] for fn in feature_names})


def plot_parity_for_target(
    X_train,
    X_test,
    y_train,
    y_test,
    models,
    target_name,
    subset="test",
    output_dir=None,
    show_plot=True,
):
    if subset == "test":
        X_used = X_test
        y_used = y_test
        subtitle = "Test data"
    else:
        X_used = pd.concat([X_train, X_test], axis=0)
        y_used = pd.concat([y_train, y_test], axis=0)
        subtitle = "Full dataset (train + test)"

    n_models = len(models)
    n_cols = 3
    n_rows = math.ceil(n_models / n_cols)

    plt.figure(figsize=(5 * n_cols, 4 * n_rows))
    plt.suptitle(f"{target_name} parity plots - {subtitle}", fontsize=16)

    for i, (name, model) in enumerate(models, start=1):
        model.fit(X_train, y_train)
        y_pred = model.predict(X_used)

        plt.subplot(n_rows, n_cols, i)
        plt.scatter(y_used, y_pred, alpha=0.7, edgecolor="k")
        min_val = min(y_used.min(), y_pred.min())
        max_val = max(y_used.max(), y_pred.max())
        plt.plot([min_val, max_val], [min_val, max_val], "r--", lw=2)
        plt.xlabel(f"True {target_name}")
        plt.ylabel(f"Predicted {target_name}")
        plt.title(name)
        plt.grid(True, alpha=0.3)

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    if output_dir is not None:
        out_dir = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / f"{target_name}_{subset}_parity.png"
        plt.savefig(out_path, dpi=150, bbox_inches="tight")
        print(f"Saved parity plot: {out_path}")
    if show_plot:
        plt.show()
    plt.close()


def run_pipeline(csv_name, feature_names, output_dir="outputs", show_plots=True):
    df = pd.read_csv(csv_name)
    missing = [c for c in feature_names if c not in df.columns]
    if missing:
        raise ValueError(f"CSV missing columns: {missing}")

    target1_name, target2_name = detect_targets(df)

    print(f"Using file: {csv_name}")
    print(f"Targets detected: {target1_name}, {target2_name}")
    print(f"Independent variables: {', '.join(feature_names)}")

    X = df[feature_names]
    y1 = df[target1_name]
    y2 = df[target2_name]

    Xtrain1, Xtest1, y1_train, y1_test = train_test_split(
        X, y1, test_size=0.2, random_state=42
    )
    Xtrain2, Xtest2, y2_train, y2_test = train_test_split(
        X, y2, test_size=0.2, random_state=42
    )

    models1 = make_models()
    models2 = make_models()

    print(f"\nResults for {target1_name}")
    for name, model in models1:
        model.fit(Xtrain1, y1_train)
        ypred = model.predict(Xtest1)
        print_metrics(name, target1_name, y1_test, ypred, dataset_label="test")
        ypred_full = model.predict(pd.concat([Xtrain1, Xtest1], axis=0))
        print_metrics(name, target1_name, pd.concat([y1_train, y1_test], axis=0), ypred_full, dataset_label="all")

    print(f"\nResults for {target2_name}")
    for name, model in models2:
        model.fit(Xtrain2, y2_train)
        ypred = model.predict(Xtest2)
        print_metrics(name, target2_name, y2_test, ypred, dataset_label="test")
        ypred_full = model.predict(pd.concat([Xtrain2, Xtest2], axis=0))
        print_metrics(name, target2_name, pd.concat([y2_train, y2_test], axis=0), ypred_full, dataset_label="all")

    lin1 = next(m for n, m in models1 if n == "Linear Regression")
    lin2 = next(m for n, m in models2 if n == "Linear Regression")
    print_linear_like_formula(lin1, target1_name, "Linear", feature_names)
    print_linear_like_formula(lin2, target2_name, "Linear", feature_names)

    poly_name = "Polynomial Regression deg2"
    poly1 = next(m for n, m in models1 if n == poly_name)
    poly2 = next(m for n, m in models2 if n == poly_name)
    print_poly_formula(poly1, target1_name, degree=2, feature_names=feature_names)
    print_poly_formula(poly2, target2_name, degree=2, feature_names=feature_names)

    ridge1 = next(m for n, m in models1 if n == "Ridge Regression")
    ridge2 = next(m for n, m in models2 if n == "Ridge Regression")
    print_linear_like_formula(ridge1, target1_name, "Ridge", feature_names)
    print_linear_like_formula(ridge2, target2_name, "Ridge", feature_names)

    newdata = example_new_row(feature_names)
    print(f"Predictions for {target1_name}")
    for name, model in models1:
        pred = float(model.predict(newdata)[0])
        print(f"{name:25s} - {target1_name} {pred:.4f}")

    print(f"\nPredictions for {target2_name}")
    for name, model in models2:
        pred = float(model.predict(newdata)[0])
        print(f"{name:25s} - {target2_name} {pred:.4f}")

    if show_plots:
        plot_parity_for_target(
            Xtrain1, Xtest1, y1_train, y1_test, models1, target_name=target1_name, subset="test", output_dir=output_dir
        )
        plot_parity_for_target(
            Xtrain1, Xtest1, y1_train, y1_test, models1, target_name=target1_name, subset="full", output_dir=output_dir
        )
        plot_parity_for_target(
            Xtrain2, Xtest2, y2_train, y2_test, models2, target_name=target2_name, subset="test", output_dir=output_dir
        )
        plot_parity_for_target(
            Xtrain2, Xtest2, y2_train, y2_test, models2, target_name=target2_name, subset="full", output_dir=output_dir
        )


def main():
    args = parse_args()
    csv_name = load_csv_path(args.csv)
    df_head = pd.read_csv(csv_name, nrows=1)
    feature_names = select_independent_params(df_head.columns, args.features)
    run_pipeline(csv_name, feature_names, output_dir=args.output_dir, show_plots=not args.no_plots)


if __name__ == "__main__":
    main()
