# -*- coding: utf-8 -*-
"""5d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12nFOaPDKQoqeX2609NqukiucHLugpW21
"""

# ================== 0. Setup & imports ==================
from google.colab import files
uploaded = files.upload()  # upload your CSV

import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

from sklearn.linear_model import LinearRegression, Ridge
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import TransformedTargetRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor

# ================== 1. Configuration & auto‑detection ==================
# Use the name of the file you just uploaded
csv_name = list(uploaded.keys())[0]

df = pd.read_csv(csv_name)

# Try known pairs of target columns
if {"thcond", "spheat"}.issubset(df.columns):
    target1_name = "thcond"
    target2_name = "spheat"
elif {"density", "visc"}.issubset(df.columns):
    target1_name = "density"
    target2_name = "visc"
else:
    raise ValueError(
        "Could not find expected target columns. "
        "File must contain either (thcond, spheat) or (density, visc)."
    )

print(f"Using file: {csv_name}")
print(f"Targets detected: {target1_name}, {target2_name}")

# ================== 2. Load data & splits ==================
df = pd.read_csv(csv_name)

X = df[["temp", "loading", "conc"]]
y1 = df[target1_name]
y2 = df[target2_name]

Xtrain1, Xtest1, y1_train, y1_test = train_test_split(
    X, y1, test_size=0.2, random_state=42
)
Xtrain2, Xtest2, y2_train, y2_test = train_test_split(
    X, y2, test_size=0.2, random_state=42
)

# ================== 3. Helpers ==================
def metrics(ytrue, ypred):
    r2 = r2_score(ytrue, ypred)
    mae = mean_absolute_error(ytrue, ypred)
    rmse = np.sqrt(mean_squared_error(ytrue, ypred))
    return r2, mae, rmse

def print_metrics(name, target, ytrue, ypred):
    r2, mae, rmse = metrics(ytrue, ypred)
    print(f"{name:25s} - {target:8s} R2={r2:.4f}, MAE={mae:.4f}, RMSE={rmse:.4f}")

def print_linear_like_formula(model, target_name, label):
    coef = model.coef_
    inter = model.intercept_
    print(f"{label} formula for {target_name}")
    print(
        f"{target_name} = {inter:.6f}"
        f" + {coef[0]:.6f}*temp"
        f" + {coef[1]:.6f}*loading"
        f" + {coef[2]:.6f}*conc"
    )
    print()

def print_poly_formula(pipe, target_name, degree):
    polystep = pipe.named_steps["poly"]
    linstep = pipe.named_steps["lin"]
    names = polystep.get_feature_names_out(["temp", "loading", "conc"])
    coefs = linstep.coef_
    inter = linstep.intercept_

    print(f"Polynomial deg{degree} formula for {target_name}")
    expr = f"{target_name} = {inter:.6f}"
    for name, c in zip(names[1:], coefs[1:]):
        expr += f" + {c:.6f}*{name}"
    print(expr)
    print()

def make_models(polydegree=2):
    return [
        ("Linear Regression", LinearRegression()),
        (f"Polynomial Regression deg{polydegree}", Pipeline([
            ("poly", PolynomialFeatures(degree=polydegree, include_bias=False)),
            ("lin", LinearRegression()),
        ])),
        ("Random Forest", RandomForestRegressor(
            n_estimators=200, random_state=42, n_jobs=-1)),
        ("Gradient Boosting", GradientBoostingRegressor(
            n_estimators=300, learning_rate=0.05, max_depth=3, random_state=42)),
        ("XGBoost", XGBRegressor(
            n_estimators=300, learning_rate=0.05, max_depth=4,
            subsample=0.9, colsample_bytree=0.9, random_state=42, n_jobs=-1)),
        ("Ridge Regression", Ridge(alpha=1.0)),
        ("KNN", KNeighborsRegressor(n_neighbors=5, weights="distance")),
        ("Neural Network", TransformedTargetRegressor(
            regressor=Pipeline([
                ("scaler", StandardScaler()),
                ("mlp", MLPRegressor(
                    hidden_layer_sizes=(64, 32), activation="relu",
                    alpha=0.05, learning_rate_init=0.001,
                    max_iter=2000, random_state=42)),
            ]),
            transformer=StandardScaler(),
        )),
        ("CatBoost", CatBoostRegressor(
            iterations=300, learning_rate=0.05, depth=6,
            random_seed=42, verbose=0)),
    ]

# ================== 4. Train models & metrics ==================
models1 = make_models()
models2 = make_models()

print(f"Results for {target1_name}")
for name, model in models1:
    model.fit(Xtrain1, y1_train)
    ypred = model.predict(Xtest1)
    print_metrics(name, target1_name, y1_test, ypred)

print(f"\nResults for {target2_name}")
for name, model in models2:
    model.fit(Xtrain2, y2_train)
    ypred = model.predict(Xtest2)
    print_metrics(name, target2_name, y2_test, ypred)

# ================== 5. Explicit formulas ==================
# Linear
lin1 = next(m for n, m in models1 if n == "Linear Regression")
lin2 = next(m for n, m in models2 if n == "Linear Regression")
print_linear_like_formula(lin1, target1_name, "Linear")
print_linear_like_formula(lin2, target2_name, "Linear")

# Polynomial degree 2
poly_name = "Polynomial Regression deg2"
poly1 = next(m for n, m in models1 if n == poly_name)
poly2 = next(m for n, m in models2 if n == poly_name)
print_poly_formula(poly1, target1_name, degree=2)
print_poly_formula(poly2, target2_name, degree=2)

# Ridge
ridge1 = next(m for n, m in models1 if n == "Ridge Regression")
ridge2 = next(m for n, m in models2 if n == "Ridge Regression")
print_linear_like_formula(ridge1, target1_name, "Ridge")
print_linear_like_formula(ridge2, target2_name, "Ridge")

# ================== 6. Predictions for a new point ==================
newdata = pd.DataFrame({
    "temp": [55.0],
    "loading": [0.3],
    "conc": [0.8],
})

print(f"Predictions for {target1_name}")
for name, model in models1:
    pred = float(model.predict(newdata)[0])
    print(f"{name:25s} - {target1_name} {pred:.4f}")

print(f"\nPredictions for {target2_name}")
for name, model in models2:
    pred = float(model.predict(newdata)[0])
    print(f"{name:25s} - {target2_name} {pred:.4f}")

# ================== 7. Parity plots (test + full) ==================
def plot_parity_for_target(X_train, X_test, y_train, y_test,
                           models, target_name, subset="test"):
    if subset == "test":
        X_used = X_test
        y_used = y_test
        subtitle = "Test data"
    else:
        X_used = pd.concat([X_train, X_test], axis=0)
        y_used = pd.concat([y_train, y_test], axis=0)
        subtitle = "Full dataset (train + test)"

    n_models = len(models)
    n_cols = 3
    n_rows = math.ceil(n_models / n_cols)

    plt.figure(figsize=(5 * n_cols, 4 * n_rows))
    plt.suptitle(f"{target_name} parity plots - {subtitle}", fontsize=16)

    for i, (name, model) in enumerate(models, start=1):
        model.fit(X_train, y_train)
        y_pred = model.predict(X_used)

        plt.subplot(n_rows, n_cols, i)
        plt.scatter(y_used, y_pred, alpha=0.7, edgecolor="k")
        min_val = min(y_used.min(), y_pred.min())
        max_val = max(y_used.max(), y_pred.max())
        plt.plot([min_val, max_val], [min_val, max_val], "r--", lw=2)
        plt.xlabel(f"True {target_name}")
        plt.ylabel(f"Predicted {target_name}")
        plt.title(name)
        plt.grid(True, alpha=0.3)

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

# target1
plot_parity_for_target(Xtrain1, Xtest1, y1_train, y1_test,
                       models1, target_name=target1_name, subset="test")
plot_parity_for_target(Xtrain1, Xtest1, y1_train, y1_test,
                       models1, target_name=target1_name, subset="full")

# target2
plot_parity_for_target(Xtrain2, Xtest2, y2_train, y2_test,
                       models2, target_name=target2_name, subset="test")
plot_parity_for_target(Xtrain2, Xtest2, y2_train, y2_test,
                       models2, target_name=target2_name, subset="full")